### ISSUE TITLE
trying to sign dll "Operation is not valid due to the current state of the object"

### ISSUE THREAD

**Issue by denfromufa** [brutaldev/StrongNameSigner#32]
I'm trying to sign Python.Runtime.DLL, but got this error:

![image](https://cloud.githubusercontent.com/assets/7870949/23033454/c2500910-f43d-11e6-973f-0ba957f08c49.png)

This used to work before and stopped working in version 1.8.0.

**Comment by brutaldev** [comment]
The latest version is [2.1.0](https://github.com/brutaldev/StrongNameSigner/releases/tag/v2.1.0) which has some significant changes to the signing. If it still breaks with the latest version let me know, I'm not supporting version 1.x.

**Comment by denfromufa** [comment]
@brutaldev yes, I checked with latest as well

**Comment by denfromufa** [comment]
@brutaldev actually not, let me check

**Comment by denfromufa** [comment]
2.1.0.0 still not working:

![image](https://cloud.githubusercontent.com/assets/7870949/23033864/4c1a1978-f43f-11e6-8fb9-91e1ec839d5e.png)

**Comment by brutaldev** [comment]
Please post a link to where I can get `Python.Runtime.DLL` to test on my side.

**Comment by denfromufa** [comment]
I just recompiled from master with Debug/AnyCPU and your tool is working!

![image](https://cloud.githubusercontent.com/assets/7870949/23034086/2f2bb1e0-f440-11e6-97ec-fb8eec590ae1.png)

**Comment by denfromufa** [comment]
you can download Python.Runtime.DLL from here, just extract .whl as zip files:

https://pypi.python.org/pypi/pythonnet/2.2.2#downloads

**Comment by brutaldev** [comment]
Hmm, could just be a messes up release then. I'll drop 2.1.1 just as a rebuild and see if that helps. I'll let you know when it's up and you can give it another test with the official version.

**Comment by brutaldev** [comment]
Give this version a try please: [https://brutaldev.com/download/StrongNameSigner_Setup.exe?v=2.1.1](https://brutaldev.com/download/StrongNameSigner_Setup.exe?v=2.1.1)

**Comment by denfromufa** [comment]
still the same error, so try downloading my DLL.

**Comment by brutaldev** [comment]
So strange, I can the `Python.Runtime.DLL` using 2.1.0 and 2.1.1 without any error. Try build in release and see if it happens on your side.

**Comment by denfromufa** [comment]
I can't build release version, it complains about sandcastle.

**Comment by brutaldev** [comment]
That will be a post build step anyway, you will still have a release build to run before that happens.

**Comment by denfromufa** [comment]
Release build from Master branch works as well.

**Comment by brutaldev** [comment]
¯\_(ツ)_/¯
Only seems to break on your machine. I've tried signing `Python.Runtime.DLL` on several machines now and cannot reproduce the error even on the current version of 2.1.0.

**Comment by denfromufa** [comment]
@brutaldev I just tried on another machine and this works with the latest installer. so me too:

¯\(ツ)/¯

**Comment by brutaldev** [comment]
I think we can chalk this up to a weird bug that only exists on your machine with compiled release versions... If anyone else gets the "_Operation is not valid due to the current state of the object_" error then just re-open this issue.

**Comment by denfromufa** [comment]
@brutaldev I just reproduced this problem on Windows 10 (before it was Windows 7). I'm using 64-bit Python 3.5 wheel:

https://pypi.python.org/packages/c2/1b/616ba08a2856537f511e052020dc2317213af031d88c8db361f26cc89f6a/pythonnet-2.2.2-cp35-cp35m-win_amd64.whl

**Comment by brutaldev** [comment]
@denfromufa Are you talking about `Python.Runtime.dll`? Just tried your download link on my machine and works without a hitch. Only seems to happen for you... If you can get it to happen consistently in the UI, click the "Show Output" link and see if there is a stack trace there which might be useful.

**Comment by GieltjE** [comment]
Can easily be fixed by releasing the AssemblyDefinition and just caching the AssemblyInfo results.

Took me about 3 minutes to figure out, let's just get this crap over with.

**Comment by brutaldev** [comment]
@GieltjE I updated to the latest pre-release of Mono.Cecil which has `IDisposable` on `AssemblyDefinition`. Also ensured they are disposed of at appropriate times but the file locking problem with the pre-release version still remains as I mentioned in issue #40. You can verify with the [unit tests](https://ci.appveyor.com/project/brutaldev/strongnamesigner) that file locks still occur so I won't be going live with this version. You can view the changes in the [mono.cecil-0.10 branch](https://github.com/brutaldev/StrongNameSigner/tree/mono.cecil-0.10).

Caching `AssemblyInfo` would be pointless since only the getter generates an instance of that class and it gets stale really fast, it would fail with the same problem long before it gets there because it still needs to read the PDB files in long before that.

Would love to see how you easily fixed this in about 3 minutes, perhaps you can provide a PR for your changes and you can get this crap over with yourself.

**Comment by GieltjE** [comment]
Works for me, just took the parts I needed, updated the assembly info to hold the hash (switched to .net sha1) to rectify the list<string,list< and properly disposed the objects both in the getassembly and signassembly.

Everthing runs fine, no more locking issues.

Using lists this way, not disposing objects, spelling mistakes, inconsistent naming scheme, closing of actual issues doesn't look like promising to me, sorry.

**Comment by GieltjE** [comment]
https://github.com/nunit/nunit3-vs-adapter/issues/325

That is the bug that prohibits the correct functioning of the test cases, otherwise with the proper disposal of the mentioned objects the new versions are perfectly fine :)

**Comment by brutaldev** [comment]
The following commit contains the changes you are referring to: https://github.com/brutaldev/StrongNameSigner/commit/9cb11ec8e77074f3e36207ebcd85095e109cdb7e

This commit properly disposes these objects and uses the beta6 version of Mono.Cecil. This may fix the PDB issue, but the new version of Mono.Cecil holds locks to files so any non-trivial signing process will fail. This is clearly highlighted by the failing tests when introducing these changes: https://ci.appveyor.com/project/brutaldev/strongnamesigner/build/tests

Although the changes you mention will fix the problem in your very simple signing process, this is not a viable solution because of the additional problems it introduces and how many other users will experience file locking issues.
